services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME:-frontend_dev} 
    build:
      context: ./front-end
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile.dev}
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_INTERNAL_PORT:-5173}"
    restart: always
    volumes:
      - ./front-end:/app 
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      
  api:
    container_name: ${API_NODE_CONTAINER_NAME:-api_node_dev}
    build:
      context: ./api-node
      dockerfile: ${API_NODE_DOCKERFILE:-Dockerfile.dev}
    ports:
      - "${API_NODE_PORT:-3000}:${API_NODE_INTERNAL_PORT:-3000}"
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
    restart: always
    depends_on:
      - postgresql
    networks:
      - network_name
    volumes:
      - ./api-node:/app  
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgresql://docker:docker@postgresql:5432/predictions-db}
      - API_PORT=${API_NODE_INTERNAL_PORT:-3000}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - FIRST_ADMIN_PASSWORD=${FIRST_ADMIN_PASSWORD:-123456abc}
      - PUBLIC_DIR=${PUBLIC_DIR:-/app/outputs}
      - UPLOAD_DIR=${UPLOAD_DIR:-/app/uploads}
      - JWT_SECRET=${JWT_SECRET:-secret}

  postgresql:
    container_name: ${DB_CONTAINER_NAME:-postgresql_db}
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-docker}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-docker}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-predictions-db}
      - POSTGRESQL_PORT_NUMBER=${POSTGRESQL_PORT_NUMBER:-5432}
    restart: always
    ports:
      - "${POSTGRESQL_HOST_PORT:-5432}:${POSTGRESQL_PORT_NUMBER:-5432}"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - network_name

  python:
    container_name: ${API_PYTHON_CONTAINER_NAME:-api_python_dev}
    build:
      context: ./api-python  
      dockerfile: ${API_PYTHON_DOCKERFILE:-Dockerfile.dev}
    restart: always
    ports:
      - "${API_PYTHON_PORT:-5000}:${API_PYTHON_INTERNAL_PORT:-5000}"
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgresql://docker:docker@postgresql:5432/predictions-db}
    volumes:
      - ./api-python:/app
    networks:
      - network_name

volumes:
  postgresql_data:
    driver: local


networks:
  network_name:
    driver: bridge