FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y vim openssl zsh git curl && apt-get clean

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN pnpm install

COPY . .

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

RUN echo "HISTFILE=/app/.zsh_history" >> /root/.zshrc
RUN echo "HISTSIZE=1000" >> /root/.zshrc
RUN echo "SAVEHIST=1000" >> /root/.zshrc
RUN echo "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)" >> /root/.zshrc
RUN echo "source /root/.oh-my-zsh/oh-my-zsh.sh" >> /root/.zshrc
RUN echo "source ${ZSH_CUSTOM:-/root/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc


EXPOSE 5173

ENV NODE_ENV=development

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
