FROM template-py-base

WORKDIR /app

COPY requirements.txt ./

RUN uv pip install --system -r requirements.txt 

COPY . .

EXPOSE 5000

CMD [ "flask", "--app", "src/main", "run", "--debug", "--host=0.0.0.0" ]